### PR TITLE
add animation on search

### PR DESCRIPTION
**Pull request by qjack001**

### CODE REVIEW

**Comment by qjack001** [comment]
wait its not right one sec let me figure out why

**Comment by qjack001** [comment]
> your h1 isn't gonna do anything because its in the scoped film vue CSS which doesn't have style you should add to the app.vue page also Error: Cannot read property 'push' of

I noticed, I'm going to fix but need to update the structure a bit

**Comment by HoloPollock** [comment]
Cool yah seems to work

**Comment by qjack001** [comment]
its a little slow. can you quickly change the animations to `1s cubic-bezier(.82,.01,.45,1)`?

**Pull request merged**
